# Generated by Django 5.2.5 on 2025-08-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poptavka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('zprava', models.TextField()),
                ('datum', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
